### ISSUE TITLE
Java 11 - java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory

### ISSUE THREAD

**Issue by Querela** [clarin-eric/fcs-sru-aggregator#26]
I tried to set up a the aggregator with Java 11 but received an error:

<details>
<summary>Output</summary>

```java
ERROR [2022-03-25 15:47:25,091] eu.clarin.sru.fcs.aggregator.scan.CenterRegistryLive: null
! java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
! at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
! at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
! at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
! at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92)
! at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125)
! at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:230)
! ... 38 common frames omitted
! Causing: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
! at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:232)
! at javax.xml.bind.ContextFinder.find(ContextFinder.java:375)
! at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
! at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
! at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getStoredJaxbContext(AbstractJaxbProvider.java:288)
! at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getJAXBContext(AbstractJaxbProvider.java:273)
! at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getUnmarshaller(AbstractJaxbProvider.java:189)
! at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getUnmarshaller(AbstractJaxbProvider.java:164)
! at org.glassfish.jersey.jaxb.internal.AbstractRootElementJaxbProvider.readFrom(AbstractRootElementJaxbProvider.java:111)
! ... 30 common frames omitted
! Causing: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
! at org.glassfish.jersey.jaxb.internal.AbstractRootElementJaxbProvider.readFrom(AbstractRootElementJaxbProvider.java:115)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
! at eu.clarin.weblicht.connectors.cmditransform.CMDIReaderInterceptor.aroundReadFrom(CMDIReaderInterceptor.java:31)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
! at io.dropwizard.jersey.gzip.GZipDecoder.aroundReadFrom(GZipDecoder.java:37)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
! at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1071)
! at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:850)
! at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:784)
! at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:297)
! at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:853)
! at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:750)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
! at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:748)
! at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:404)
! at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:300)
! at eu.clarin.weblicht.connectors.cr.CenterRegistryConnector.retrieveCenters(CenterRegistryConnector.java:42)
! ... 9 common frames omitted
! Causing: eu.clarin.weblicht.connectors.ConnectorException: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
! at eu.clarin.weblicht.connectors.cr.CenterRegistryConnector.retrieveCenters(CenterRegistryConnector.java:47)
! at eu.clarin.sru.fcs.aggregator.scan.CenterRegistryLive.loadCQLInstitutions(CenterRegistryLive.java:51)
! at eu.clarin.sru.fcs.aggregator.scan.CenterRegistryLive.getCQLInstitutions(CenterRegistryLive.java:87)
! at eu.clarin.sru.fcs.aggregator.scan.ScanCrawlTask.run(ScanCrawlTask.java:70)
! at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
! at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
! at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
! at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

I found that this SO answer helped: https://stackoverflow.com/a/61283181/9360161
Add the required dependencies to the `pom.xml`, rebuild and no error appears.

**Comment by Querela** [comment]
Used in #51 / 5231360996c494ca2b3cc66d6f4e496baed77827 .
